print("Challenge 11")
birthCity = input("Where were you born? (single word answers please(like don't put 'I was born in...')) ")
age = input("How old are you? (number answers please) ")
flavor = input("What is your favorite icecream flavor? (single flavor answers please) ")
movie = input("What is your favorite movie? (single movie answers please) ")
color = input("What is your favorite color? (single color answers please) ")

print("I have learned from you that:")
print("You were born in " + birthCity)
print("You are " + age + " years old and you love " + flavor + " ice cream")
print("I think that maybe one day we can watch " + movie + " together")
