print("A fairy tale always starts with “Once upon a time” and ends with “THE END”.")
print("If you get all TRUE, it is a valid fairytale, otherwise it is not a fairytale.")
print("Please type your Fairy Tale:")
story = input("")
print(story.startswith("Once upon a time"))
print(story.endswith("THE END"))
